### ISSUE TITLE
Ruby Quote Support

### ISSUE THREAD

**Issue by tleish** [danielkurecka/intellij-extra-actions#1]
Great plugin.  Can you add quote support for ruby (aka IntelliJ Rubymine)?

**Comment by danielkurecka** [comment]
I'm afraid I'm not able to do that.

The action "Toggle Quotes" works by invoking language specific intention, which does the actual replacement of single/double quotes. Unfortunately there is no such an intention available for ruby, and I'm not experienced enough to implement it by myself.

**Comment by tleish** [comment]
They have an intention for converting double quotes to single quotes.

Also, I believe all IntelliJ IDEs have the following steps for converting single to double, or double to single, regardless of the language.

1. Select quoted string, including quotes (either with the cursor or by placing cursor in middle of the string and pressing ALT+UP ARROW until string and quotes are selected).
2. Type the alternate quote you want ( eg ' or " ).  This will change the quoted string to whichever quote you want.

WIth this, you might be able to make the toggle quoting supported for all languages.

**Comment by danielkurecka** [comment]
So I did look into it a little bit more and actually implemented something that should work. It will be published soon.

**Comment by tleish** [comment]
Fantastic!

**Comment by tleish** [comment]
Update works great in ruby code on Rubymine.  This is one of the features that should become default of the main IDE.

Thanks!
