### ISSUE TITLE
Keyboard Shortcut Not Working for Split Selection into Lines 

### ISSUE THREAD

**Issue by tleish** [danielkurecka/intellij-extra-actions#4]
I upgraded RubyMine from 2019.3.4 to 2020.1.  I assigned several keyboard shortcuts to various Extra Actions (Break Quotes, Select in Project, Split Selection, Split Selection into Lines, Toggle Quotes).  All of my keyboard shortcuts work except for Split Selection into Lines (which I use often).

I tested the following:

1. Change keyboard for Split Selection into Lines to a different key combination > FAILED
2. Remove the keyboard shortcut from Split Selection into Lines and try the same shortcut on a Break Quotes > SUCCESS
3. Help > Find Action > Split Selection into Lines > SUCCESS

So, from the above tests I know the following:
1. The keyboard shortcut is valid
2. The action still works if run from "Find Action"
3. Various keyboard shortcuts do not work on Split Selection into Line, but work on other actions.

Thoughts?

**Comment by danielkurecka** [comment]
Hi, I just tried it with fresh installation of RubyMine 2020.1 on Ubuntu and it works fine for me. Not sure what could be the issue.

Maybe try set the keyboard shortcut in different keymap profile or you could try to do FIle | Invalidate Caches/Restart.

**Comment by tleish** [comment]
Good tip on the Invalidate Cache/Restart.  It's now working for me.
